# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# https://support.atlassian.com/bitbucket-cloud/docs/laravel-with-bitbucket-pipelines/
image: node:10.22.1-stretch

options:
  max-time: 10

definitions:
  caches:
    vendor: vendor

pipelines:
  branches:
    master:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm i
            - npm i --save vue-class-component
            - npm run build:prod
          artifacts:
            - dist/**
      - step:
          name: Publish
          deployment: Production-SCP
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: ${USER_APP}
                SERVER: ${SERVER_APP}
                REMOTE_PATH: ${PATH_APP}
                LOCAL_PATH: ${LOCAL_PATH}
    staging:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm i
            - npm i --save vue-class-component
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Publish
          deployment: Staging-SCP
          script:
            - pipe: atlassian/scp-deploy:0.3.12
              variables:
                USER: ${USER_APP}
                SERVER: ${SERVER_APP}
                REMOTE_PATH: ${PATH_APP}
                LOCAL_PATH: ${LOCAL_PATH}
