# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: vuejs/ci:latest

options:
  max-time: 60

pipelines:
  branches:
    master:
      - step:
          name: Build
          script:
            - npm i -g --unsafe-perm --no-interactive increase-memory-limit @vue/cli
            - npm i
            - npm i --save vue-class-component
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Build
          deployment: production
          script:
            - pipe: atlassian/scp-deploy:0.3.3
              variables:
                USER: $USER
                SERVER: $SERVER
                REMOTE_PATH: '/opt'
                LOCAL_PATH: 'dist/*'
